### PR TITLE
Use MediaWiki cache strategy and code

### PR DESCRIPTION
**Pull request by rdalverny**
This removes all BugzillaCache\* classes and code that used it, replaces it with MediaWiki `wfGetCache($wgMainCacheType)`, which provides sensibly the same set of options.

Doing so simplifies a first install, by removing specific configuration for this extension; and reduces the code base.

### CODE REVIEW

**Comment by LegNeato** [comment]
Again, sorry for the delay! Does this affect the min version of mediawiki supported? We'll also need someone from mozilla to confirm that they use wfGetCache and their installation will continue to work.

**Comment by rdalverny** [comment]
> Again, sorry for the delay!

No worries!

> Does this affect the min version of mediawiki supported?

`wfGetCache` has been last refactored in https://github.com/wikimedia/mediawiki/commit/be76d86932bea59ea18d729b28d05fbc4775cf25 in March 2011.  So any MW 1.16+ is fine. What is the current min version supported at this point?

> We'll also need someone from mozilla to confirm that they use wfGetCache and their installation will continue to work.

Yes! Maybe I can add a section in the README about this (configuring `$wgMainCacheType`).

**Comment by LegNeato** [comment]
I'm not sure who to ping for mozwiki...most of the bugs look like they haven't been touched in a bit. @christi3k? Or do you have any pointers to someone else? Thanks!

**Comment by dennisroczek** [comment]
well for the case I will have time to finish my pull request then the min MW1.23+ requirement would be 
https://github.com/mozilla/mediawiki-bugzilla/pull/80

Moreover we finally could use JQuerry from MediaWiki itself (see #26) :-)

**Comment by hexmode** [comment]
I don't think @christi3k is going to be available to help.  I think I have the right to merge pull requests.

MozWiki should be updated to the latest LTS since 1.23 is being EOL'd in May.  See https://www.mediawiki.org/wiki/Version_lifecycle#Versions_and_their_end-of-life

**Comment by LegNeato** [comment]
Lets get this one in, sorry for the delay!

**Comment by rdalverny** [comment]
Thank you! 😄

**Pull request merged**
